import type { AppProps } from "next/app";
import { Nunito } from "next/font/google";

import ReactQueryContainer from "../container/ReactQueryContainer";
import Layout from "../components/layout";
import Head from "next/head";

import "../styles/index.css";

const nunito = Nunito({ subsets: ["latin"] });

export default function App({ Component, pageProps }: AppProps) {
  return (
    <main className={nunito.className}>
      <Head>
        <title>Store chic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReactQueryContainer dehydratedState={pageProps.dehydratedState}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </ReactQueryContainer>
    </main>
  );
}
