import Head from "next/head";
import { Nunito } from "next/font/google";
import Hero from "@/components/Hero";
import ProductList from "@/components/ProductList";
import useProduct from "@/store/useProduct";
import { useGetProduct } from "@/querys/productQuerys";

const nunito = Nunito({ subsets: ["latin"] });

export default function Home() {
  const { addToCart: addToCard, isProductInCart } = useProduct();

  const { data = [], isLoading } = useGetProduct();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={nunito.className}>
        <Hero />
        <ProductList
          data={data}
          isLoading={isLoading}
          onClick={addToCard}
          isProductInCart={isProductInCart}
        />
      </main>
    </>
  );
}
